apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::975049981118:user/github-actions
      username: github-actions
      groups:
        - system:masters
